### PR TITLE
Skip collapse on init if expandedClass is set.

### PR DESCRIPTION
**Pull request by koddsson**
This patch will not collapse the container if the `expandedClass` is set. Makes it possible to initialize a page without auto collapsing.

### CODE REVIEW

**Comment by eirikurn** [comment]
Cool! We obviously forgot this use case.

I guess it can check if the class is already set, but there should probably be a plugin option for it as well. Something like this?

```
<div data-expand-toggle="collapsed"></div>
<div data-expand-toggle data-initial="collapsed"></div>
```

In any case, the implementation is a bit more tricky, as `#maxHeight` will not be set correctly if the container is collapsed, and `#isExpanded` will be false-ish. It should probably call `#expand()` instead of doing nothing but we need to figure out what to do with max-height.

**Comment by koddsson** [comment]
I just pushed changes that deal with both the plugin option issue and the `isExpanded` variable but I'm not sure how `maxHeight` is affected. The value looks to me to be the same on the example page for each instance of the plugin with this patch applied and not applied.

**Comment by eirikurn** [comment]
Ah, I see how that's not a problem in this case. I still feel a bit dirty about how maxHeight is calculated and cached forever - seems unresponsive. But that's an issue for another issue :)

I assume that `glob` is needed and was missing for some reason.

Please don't add env specific stuff to .gitignore. Actually, `.DS_Store` shouldn't even be there. You should create a [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) for those instead. Please fix this and then I'll merge.

**Comment by eirikurn** [comment]
LGTM

[LGTM](http://www.lgtm.in/i/A8zH418nq)

**Comment by koddsson** [comment]
Good point about the `.gitignore` ;)

**Pull request merged**
