### PR TITLE
Overflow auto on expand and set text

### PR DESCRIPTION
**Pull request by koddsson**
Okkkk so this is something that I needed in my project but I haven't still convinced myself it should live in this component.

This patch does two things:
1. It will set the `overflow` of the container to `auto` when it is expanded to make sure that you can scroll within the container when expanded beyond `maxHeight`. If you don't have `maxHeight` set this will have no effect.
2. It enables you to set `data-expanded-text` to a string that will replace the text in the `el` element when expanded and then replace _that_ text with the original when collapsing.

I feel like 1. is probably cool but 2. feel a bit hackish to me so I figure I'd open up a PR and see what you think! :)

### CODE REVIEW

**Comment by eirikurn** [comment]
Cool. Thanks for the PR.

I think 1 is more properly solved with css using `expandedClass`.

```
.is-expanded .Toggle-content {
  overflow: auto;
}
```

Nr 2 is actually interesting and I think it's a very common use case. God knows I've needed this before. Only question is if there is a better way and if this is a wormhole of different needs ("I need different icons, different markup, etc").

**Comment by eirikurn** [comment]
@aranja/tux how would you switch between "Open" and "Close". I think we've done this kind of attribute before, right?

**Comment by koddsson** [comment]
> I think 1 is more properly solved with css using `expandedClass`.

That makes waaay more sense. I'll remove that from the PR and see what the discussion from the tux group yields in regards to nr. 2. The wormhole of different needs was definitely something I was thinking about.

**Comment by koddsson** [comment]
One question abuot the CSS snippet you posted. I'm gonna run into problem if I have nested state-toggles, right?

I currently have a state-toggle in a state-toggle and the CSS rule is always enforced even though the element that I'm looking for isn't expanded. I'm bad at explaining stuff so here is some code.

``` html
<div class='Parent is-expanded'>
  <div class='Toggle' data-expand-toggle data-parent='.Parent'>Open</div>
  <ul class='Toggle-content'>
    <li>
      <div class='List'>
        <div class='Toggle' data-expand-toggle data-parent='.List'>Open</div>
        <ul class='Toggle-content'>
          <li>A thing</li>
        </ul>
      </div>
    </li>
  </ul>
</div>
```

The CSS rule is always gonna be applied to the second `.Toggle-content` since it is a child element of `.is-expanded`.

**Comment by rthor** [comment]
In case of nested togglers, you could use a direct children selector `>` to make sure the inner toggler isn't  affected:

``` css
.is-expanded > .Toggle-content {
  overflow: auto;
}
```

**Comment by rthor** [comment]
I've been thinking over number 2 and I'm not sure if this component should be responsible for that. And like @eirikurn said, I believe it'll entangle a wormhole of scenarios for which it'll be hard to generalize. But this definitely might come in handy. It would however break the code example that you (@koddsson) just showed.

Maybe the component should emit some event upon toggling its state so that some other component/script could handle the replacement of data? Not sure how that will interact with the `data–` API.

As an afterthought: In what case would you want to change the contents of a collapsed element? Maybe if the collapsed state is not of height 0? Just wondering…

**Comment by koddsson** [comment]
I'm gonna close this PR and I'll probably make another one tackling this problem in a different way.

**Comment by eirikurn** [comment]
@rthor I'm not sure if you understood 2 correctly. He meant to replace the trigger text, not the contents of the collapsed element. This makes sense as most designs have a different trigger for expanding than collapsing, be it an reversed arrow icon or a "Open"/"Close" text.

I'm reluctant to push the responsibility to much on the dev, managing event communication between components. Instead we should figure out a good way to make this easy, as it's so common. 

One way is to have both states in the markup as different elements and show/hide with css. Not sure if that's semantically ok.

``` html
<div class='Parent is-expanded'>
  <div class='Toggle' data-expand-toggle>
    <span class="Toggle-expand">Open</span>
    <span class="Toggle-collapse">Close</span>
  </div>
  <div class='Toggle-content'>
    Yo yo yo!
  </div>
</div>
```

``` css
.Toggle-collapse { display: none; }
.Toggle.is-expanded .Toggle-expand { display: none; }
.Toggle.is-expanded .Toggle-collapse { display: block; }
/* note, needs a more explicit selector to support nested toggles. */
```

**Comment by rthor** [comment]
Ahh yeah sorry, misunderstood it. Well that makes much more sense!
We've done it this way before, i.e. having both states in the markup. Makes it simple to edit and have different behavior without having to rely on JS, data attributes, etc.

So my +1 for the "states-in-markup" solution.

My only concern atm. is accessibility. Screen reader will read "Open, Close, ..." so we might want to handle that edgecase somehow. Also on the hidden content, they probably should have `aria-hidden` while being hidden. Well this is probably a topic for another pull request.

**Comment by eirikurn** [comment]
@thorsteinsson what do you think. Are we rightfully concerned about accessibility with the "states-in-markup" solution, and is there something we can do to resolve those concerns?

**Comment by thorsteinsson** [comment]
I think that having the states in the markup is much more flexible. That can handle text and whatever else you want.
We are going to need javascript to toggle the aria attributes though.

**Comment by thorsteinsson** [comment]
I think we can just add the states in markup solution you posted and improve overall accessibility in another PR.

**Comment by eirikurn** [comment]
Ok, there actually isn't any css in this component (yet?). So I'll make a issue to at least document this.

**Pull request closed without merging**
